M48
; DRILL file {KiCad 9.0.4} date 2025-08-28T11:20:26+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-28T11:20:26+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1181
%
G90
G05
T1
X6.5787Y-3.2726
X6.5787Y-3.5876
T2
X6.5089Y-4.3504
T3
X6.5089Y-4.0571
T4
X5.1841Y-5.5246
X5.6211Y-5.5246
X6.0581Y-5.5246
X6.4951Y-5.5246
M30
