name: Build PCB

on:
  push:
    branches:
      - '**'
    paths:
      - 'device/hardware/**'
  workflow_call:
  workflow_dispatch:
  
jobs:
  build-pcb-monolith:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          sudo add-apt-repository ppa:kicad/kicad-9.0-releases
          sudo apt-get update
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: kicad imagemagick
          version: 1.0

      - name: Build PCB schematic, artwork and 3d models
        run: |
          sudo apt-get install imagemagick
          npm i -g svgexport
          mkdir -p kicad
          kicad-cli sch export svg device/hardware/monolith/monolith.kicad_sch -o kicad --exclude-drawing-sheet --no-background-color
          kicad-cli pcb export svg device/hardware/monolith/monolith.kicad_pcb -o kicad/monolith-artwork.svg --layers "B.Cu,B.Silkscreen,F.Cu,F.Silkscreen,Edge.Cuts" --exclude-drawing-sheet
          svgexport kicad/monolith.svg kicad/monolith-schematic-transparent.png 8000:
          convert kicad/monolith-schematic-transparent.png -trim -bordercolor transparent -border 100x100 kicad/monolith-schematic-transparent.png
          svgexport kicad/monolith.svg kicad/monolith-schematic.png 8000: "svg{background:white;}"
          convert kicad/monolith-schematic.png -trim -bordercolor white -border 100x100 kicad/monolith-schematic.png
          mv kicad/monolith.svg kicad/monolith-schematic.svg
          svgexport kicad/monolith-artwork.svg kicad/monolith-artwork-transparent.png 8000:
          convert kicad/monolith-artwork-transparent.png -trim -bordercolor transparent -border 100x100 kicad/monolith-artwork-transparent.png
          svgexport kicad/monolith-artwork.svg kicad/monolith-artwork.png 8000: "svg{background:#001023;}"
          convert kicad/monolith-artwork.png -trim -bordercolor "#001023" -border 100x100 kicad/monolith-artwork.png
          kicad-cli pcb export step -o kicad/monolith-3d.stp --include-tracks device/hardware/monolith/monolith.kicad_pcb || true
          kicad-cli pcb export vrml -o kicad/monolith-3d.wrl device/hardware/monolith/monolith.kicad_pcb || true
          cp -r device/hardware/monolith/jlcpcb/production_files kicad/gerbers
          rm kicad/*.svg

      - uses: actions/upload-artifact@v5
        with:
          name: pcb-monolith
          path: kicad

  build-pcb-monolith-mini:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          sudo add-apt-repository ppa:kicad/kicad-9.0-releases
          sudo apt-get update
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: kicad imagemagick
          version: 1.0

      - name: Build PCB schematic, artwork and 3d models
        run: |
          sudo apt-get install imagemagick
          npm i -g svgexport
          mkdir -p kicad
          kicad-cli sch export svg device/hardware/monolith-mini/monolith-mini.kicad_sch -o kicad --exclude-drawing-sheet --no-background-color
          kicad-cli pcb export svg device/hardware/monolith-mini/monolith-mini.kicad_pcb -o kicad/monolith-mini-artwork.svg --layers "B.Cu,B.Silkscreen,F.Cu,F.Silkscreen,Edge.Cuts" --exclude-drawing-sheet
          svgexport kicad/monolith-mini.svg kicad/monolith-mini-schematic-transparent.png 8000:
          convert kicad/monolith-mini-schematic-transparent.png -trim -bordercolor transparent -border 100x100 kicad/monolith-mini-schematic-transparent.png
          svgexport kicad/monolith-mini.svg kicad/monolith-mini-schematic.png 8000: "svg{background:white;}"
          convert kicad/monolith-mini-schematic.png -trim -bordercolor white -border 100x100 kicad/monolith-mini-schematic.png
          mv kicad/monolith-mini.svg kicad/monolith-mini-schematic.svg
          svgexport kicad/monolith-mini-artwork.svg kicad/monolith-mini-artwork-transparent.png 8000:
          convert kicad/monolith-mini-artwork-transparent.png -trim -bordercolor transparent -border 100x100 kicad/monolith-mini-artwork-transparent.png
          svgexport kicad/monolith-mini-artwork.svg kicad/monolith-mini-artwork.png 8000: "svg{background:#001023;}"
          convert kicad/monolith-mini-artwork.png -trim -bordercolor "#001023" -border 100x100 kicad/monolith-mini-artwork.png
          kicad-cli pcb export step -o kicad/monolith-mini-3d.stp --include-tracks device/hardware/monolith-mini/monolith-mini.kicad_pcb || true
          kicad-cli pcb export vrml -o kicad/monolith-mini-3d.wrl device/hardware/monolith-mini/monolith-mini.kicad_pcb || true
          cp -r device/hardware/monolith-mini/jlcpcb/production_files kicad/gerbers
          rm kicad/*.svg

      - uses: actions/upload-artifact@v5
        with:
          name: pcb-monolith-mini
          path: kicad
