name: Release

on:
  push:
    tags:
      - v*

jobs:
  build-firmware:
    uses: ./.github/workflows/firmware.yml
  build-pcb:
    uses: ./.github/workflows/pcb.yml
  release:
    name: release
    runs-on: ubuntu-latest
    needs: [build-firmware, build-pcb]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
      - run: |
          mkdir -p firmware
          mv firmware-monolith firmware/monolith
          mv firmware-monolith-mini firmware/monolith-mini
          mkdir -p pcb
          mv pcb-monolith pcb/monolith
          mv pcb-monolith-mini pcb/monolith-mini
          mv .github/scripts/flash.* .
          zip -r monolith-${{ github.ref_name }}.zip pcb firmware flash.*
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: monolith-${{ github.ref_name }}.zip
          commit: ${{ github.sha }}
          tag: ${{ github.ref_name }}
          body: |
            ### Monolith ${{ github.ref_name }}
            Please read documentation at https://v2.monolith.luftaquila.io/docs/
